/*
 * This file is generated by jOOQ.
*/
package org.jooq.codes.foobar.cv;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.codes.foobar.cv.tables.Employer;
import org.jooq.codes.foobar.cv.tables.records.EmployerRecord;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EmployerRecord, Integer> IDENTITY_EMPLOYER = Identities0.IDENTITY_EMPLOYER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EmployerRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<EmployerRecord, Integer> IDENTITY_EMPLOYER = createIdentity(Employer.EMPLOYER, Employer.EMPLOYER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<EmployerRecord> CONSTRAINT_7 = createUniqueKey(Employer.EMPLOYER, "CONSTRAINT_7", Employer.EMPLOYER.ID);
    }
}
