/*
 * This file is generated by jOOQ.
*/
package org.jooq.codes.foobar.cv;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.codes.foobar.cv.tables.Education;
import org.jooq.codes.foobar.cv.tables.Employer;
import org.jooq.codes.foobar.cv.tables.Experience;
import org.jooq.codes.foobar.cv.tables.Expertise;
import org.jooq.codes.foobar.cv.tables.Person;
import org.jooq.codes.foobar.cv.tables.Project;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1664794025;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.EDUCATION</code>.
     */
    public final Education EDUCATION = org.jooq.codes.foobar.cv.tables.Education.EDUCATION;

    /**
     * The table <code>public.EMPLOYER</code>.
     */
    public final Employer EMPLOYER = org.jooq.codes.foobar.cv.tables.Employer.EMPLOYER;

    /**
     * The table <code>public.EXPERIENCE</code>.
     */
    public final Experience EXPERIENCE = org.jooq.codes.foobar.cv.tables.Experience.EXPERIENCE;

    /**
     * The table <code>public.EXPERTISE</code>.
     */
    public final Expertise EXPERTISE = org.jooq.codes.foobar.cv.tables.Expertise.EXPERTISE;

    /**
     * The table <code>public.PERSON</code>.
     */
    public final Person PERSON = org.jooq.codes.foobar.cv.tables.Person.PERSON;

    /**
     * The table <code>public.PROJECT</code>.
     */
    public final Project PROJECT = org.jooq.codes.foobar.cv.tables.Project.PROJECT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Education.EDUCATION,
            Employer.EMPLOYER,
            Experience.EXPERIENCE,
            Expertise.EXPERTISE,
            Person.PERSON,
            Project.PROJECT);
    }
}
