/*
 * This file is generated by jOOQ.
*/
package org.jooq.codes.foobar.cv;


import javax.annotation.Generated;

import org.jooq.codes.foobar.cv.tables.Employer;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.EMPLOYER</code>.
     */
    public static final Employer EMPLOYER = org.jooq.codes.foobar.cv.tables.Employer.EMPLOYER;
}
