/*
 * This file is generated by jOOQ.
*/
package org.jooq.codes.foobar.cv;


import javax.annotation.Generated;

import org.jooq.codes.foobar.cv.tables.Education;
import org.jooq.codes.foobar.cv.tables.Employer;
import org.jooq.codes.foobar.cv.tables.Experience;
import org.jooq.codes.foobar.cv.tables.Expertise;
import org.jooq.codes.foobar.cv.tables.Person;
import org.jooq.codes.foobar.cv.tables.Project;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.EDUCATION</code>.
     */
    public static final Education EDUCATION = org.jooq.codes.foobar.cv.tables.Education.EDUCATION;

    /**
     * The table <code>public.EMPLOYER</code>.
     */
    public static final Employer EMPLOYER = org.jooq.codes.foobar.cv.tables.Employer.EMPLOYER;

    /**
     * The table <code>public.EXPERIENCE</code>.
     */
    public static final Experience EXPERIENCE = org.jooq.codes.foobar.cv.tables.Experience.EXPERIENCE;

    /**
     * The table <code>public.EXPERTISE</code>.
     */
    public static final Expertise EXPERTISE = org.jooq.codes.foobar.cv.tables.Expertise.EXPERTISE;

    /**
     * The table <code>public.PERSON</code>.
     */
    public static final Person PERSON = org.jooq.codes.foobar.cv.tables.Person.PERSON;

    /**
     * The table <code>public.PROJECT</code>.
     */
    public static final Project PROJECT = org.jooq.codes.foobar.cv.tables.Project.PROJECT;
}
