/*
 * This file is generated by jOOQ.
*/
package org.jooq.codes.foobar.cv.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.codes.foobar.cv.Indexes;
import org.jooq.codes.foobar.cv.Keys;
import org.jooq.codes.foobar.cv.Public;
import org.jooq.codes.foobar.cv.tables.records.EducationRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Education extends TableImpl<EducationRecord> {

    private static final long serialVersionUID = 186970178;

    /**
     * The reference instance of <code>public.EDUCATION</code>
     */
    public static final Education EDUCATION = new Education();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EducationRecord> getRecordType() {
        return EducationRecord.class;
    }

    /**
     * The column <code>public.EDUCATION.ID</code>.
     */
    public final TableField<EducationRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.EDUCATION.PERSON_ID</code>.
     */
    public final TableField<EducationRecord, Integer> PERSON_ID = createField("PERSON_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.EDUCATION.COURSE</code>.
     */
    public final TableField<EducationRecord, Boolean> COURSE = createField("COURSE", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.EDUCATION.START_DATE</code>.
     */
    public final TableField<EducationRecord, Date> START_DATE = createField("START_DATE", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>public.EDUCATION.END_DATE</code>.
     */
    public final TableField<EducationRecord, Date> END_DATE = createField("END_DATE", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.EDUCATION.DESCRIPTION</code>.
     */
    public final TableField<EducationRecord, String> DESCRIPTION = createField("DESCRIPTION", org.jooq.impl.SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * Create a <code>public.EDUCATION</code> table reference
     */
    public Education() {
        this(DSL.name("EDUCATION"), null);
    }

    /**
     * Create an aliased <code>public.EDUCATION</code> table reference
     */
    public Education(String alias) {
        this(DSL.name(alias), EDUCATION);
    }

    /**
     * Create an aliased <code>public.EDUCATION</code> table reference
     */
    public Education(Name alias) {
        this(alias, EDUCATION);
    }

    private Education(Name alias, Table<EducationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Education(Name alias, Table<EducationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_9, Indexes.PRIMARY_KEY_9);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EducationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EDUCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EducationRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EducationRecord>> getKeys() {
        return Arrays.<UniqueKey<EducationRecord>>asList(Keys.CONSTRAINT_9);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EducationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EducationRecord, ?>>asList(Keys.CONSTRAINT_94);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Education as(String alias) {
        return new Education(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Education as(Name alias) {
        return new Education(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Education rename(String name) {
        return new Education(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Education rename(Name name) {
        return new Education(name, null);
    }
}
