/*
 * This file is generated by jOOQ.
*/
package org.jooq.codes.foobar.cv.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.codes.foobar.cv.Indexes;
import org.jooq.codes.foobar.cv.Keys;
import org.jooq.codes.foobar.cv.Public;
import org.jooq.codes.foobar.cv.tables.records.ExperienceRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Experience extends TableImpl<ExperienceRecord> {

    private static final long serialVersionUID = -1232356676;

    /**
     * The reference instance of <code>public.EXPERIENCE</code>
     */
    public static final Experience EXPERIENCE = new Experience();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExperienceRecord> getRecordType() {
        return ExperienceRecord.class;
    }

    /**
     * The column <code>public.EXPERIENCE.ID</code>.
     */
    public final TableField<ExperienceRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.EXPERIENCE.PERSON_ID</code>.
     */
    public final TableField<ExperienceRecord, Integer> PERSON_ID = createField("PERSON_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.EXPERIENCE.START_DATE</code>.
     */
    public final TableField<ExperienceRecord, Date> START_DATE = createField("START_DATE", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>public.EXPERIENCE.END_DATE</code>.
     */
    public final TableField<ExperienceRecord, Date> END_DATE = createField("END_DATE", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.EXPERIENCE.DESCRIPTION</code>.
     */
    public final TableField<ExperienceRecord, String> DESCRIPTION = createField("DESCRIPTION", org.jooq.impl.SQLDataType.VARCHAR(60), this, "");

    /**
     * Create a <code>public.EXPERIENCE</code> table reference
     */
    public Experience() {
        this(DSL.name("EXPERIENCE"), null);
    }

    /**
     * Create an aliased <code>public.EXPERIENCE</code> table reference
     */
    public Experience(String alias) {
        this(DSL.name(alias), EXPERIENCE);
    }

    /**
     * Create an aliased <code>public.EXPERIENCE</code> table reference
     */
    public Experience(Name alias) {
        this(alias, EXPERIENCE);
    }

    private Experience(Name alias, Table<ExperienceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Experience(Name alias, Table<ExperienceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_1, Indexes.PRIMARY_KEY_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExperienceRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EXPERIENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExperienceRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExperienceRecord>> getKeys() {
        return Arrays.<UniqueKey<ExperienceRecord>>asList(Keys.CONSTRAINT_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ExperienceRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ExperienceRecord, ?>>asList(Keys.CONSTRAINT_17);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Experience as(String alias) {
        return new Experience(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Experience as(Name alias) {
        return new Experience(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Experience rename(String name) {
        return new Experience(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Experience rename(Name name) {
        return new Experience(name, null);
    }
}
