/*
 * This file is generated by jOOQ.
*/
package org.jooq.codes.foobar.cv.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.codes.foobar.cv.tables.Employer;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployerRecord extends UpdatableRecordImpl<EmployerRecord> implements Record4<Integer, String, Date, Date> {

    private static final long serialVersionUID = 1018208535;

    /**
     * Setter for <code>public.EMPLOYER.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.EMPLOYER.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.EMPLOYER.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.EMPLOYER.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.EMPLOYER.STARTED</code>.
     */
    public void setStarted(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.EMPLOYER.STARTED</code>.
     */
    public Date getStarted() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>public.EMPLOYER.ENDED</code>.
     */
    public void setEnded(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.EMPLOYER.ENDED</code>.
     */
    public Date getEnded() {
        return (Date) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Date, Date> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Date, Date> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Employer.EMPLOYER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Employer.EMPLOYER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Employer.EMPLOYER.STARTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return Employer.EMPLOYER.ENDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployerRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployerRecord value3(Date value) {
        setStarted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployerRecord value4(Date value) {
        setEnded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployerRecord values(Integer value1, String value2, Date value3, Date value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployerRecord
     */
    public EmployerRecord() {
        super(Employer.EMPLOYER);
    }

    /**
     * Create a detached, initialised EmployerRecord
     */
    public EmployerRecord(Integer id, String name, Date started, Date ended) {
        super(Employer.EMPLOYER);

        set(0, id);
        set(1, name);
        set(2, started);
        set(3, ended);
    }
}
