/*
 * This file is generated by jOOQ.
*/
package org.jooq.codes.foobar.cv.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.codes.foobar.cv.tables.Experience;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperienceRecord extends UpdatableRecordImpl<ExperienceRecord> implements Record5<Integer, Integer, Date, Date, String> {

    private static final long serialVersionUID = -569772809;

    /**
     * Setter for <code>public.EXPERIENCE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.EXPERIENCE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.EXPERIENCE.PERSON_ID</code>.
     */
    public void setPersonId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.EXPERIENCE.PERSON_ID</code>.
     */
    public Integer getPersonId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.EXPERIENCE.START_DATE</code>.
     */
    public void setStartDate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.EXPERIENCE.START_DATE</code>.
     */
    public Date getStartDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>public.EXPERIENCE.END_DATE</code>.
     */
    public void setEndDate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.EXPERIENCE.END_DATE</code>.
     */
    public Date getEndDate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>public.EXPERIENCE.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.EXPERIENCE.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Date, Date, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Date, Date, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Experience.EXPERIENCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Experience.EXPERIENCE.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Experience.EXPERIENCE.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return Experience.EXPERIENCE.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Experience.EXPERIENCE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value2(Integer value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value3(Date value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value4(Date value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord values(Integer value1, Integer value2, Date value3, Date value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExperienceRecord
     */
    public ExperienceRecord() {
        super(Experience.EXPERIENCE);
    }

    /**
     * Create a detached, initialised ExperienceRecord
     */
    public ExperienceRecord(Integer id, Integer personId, Date startDate, Date endDate, String description) {
        super(Experience.EXPERIENCE);

        set(0, id);
        set(1, personId);
        set(2, startDate);
        set(3, endDate);
        set(4, description);
    }
}
